name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 Complete!"
      - name: Step 2
        run: echo "Step 2 Complete!"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: gr2m/cowsay-action@v1.x
        with:
          text: "Ready for prod-ship it!"